1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. 
Expected Output: 
Original List: [12.23, 13.32, 100, 36.32] 
One-dimensional numpy array: [ 12.23 13.32 100. 36.32] 

In [1]:
import numpy as np
lst = [12.23, 13.32, 100, 36.32]
np1 = np.array(lst)
print("list : ",lst,type(lst))
print("numpy array : ",np1,np1.dtype)

list :  [12.23, 13.32, 100, 36.32] <class 'list'>
numpy array :  [ 12.23  13.32 100.    36.32] float64


2. Create a 3x3 matrix with values ranging from 2 to 10. 
Expected Output: 
[[ 2 3 4] 
[ 5 6 7] 
[ 8 9 10]] 

In [2]:
np1 = np.arange(2,11).reshape(3,3)
print(np1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11. [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
Update sixth value to 11 
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [3]:
np1 = np.zeros(10)
np1[6]=11
print(np1)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] 
Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12] 

In [4]:
np1 = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print("Original Array : ",np1)
print("Reverse Array : ",np1[::-1])

Original Array :  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array :  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside. Expected Output: 
Original array: 
[[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.] 
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array 
[[ 1. 1. 1. 1. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 1. 1. 1. 1.]] 


In [5]:
np1 = np.ones(25).reshape(5,5)
print("Original Array : \n",np1)
np2 = np.zeros(9).reshape(3,3)
print("np2 : \n",np2)
np1[1:4,1:4]=np2
print("Expected : \n",np1)

Original Array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
np2 : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Expected : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array. Expected Output: 
Original array: 
[[ 1. 1. 1.] 
[ 1. 1. 1.] 
[ 1. 1. 1.]] 
1 on the border and 0 inside in the array 
[[ 0. 0. 0. 0. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 1. 1. 1. 0.] 
[ 0. 0. 0. 0. 0.]] 


In [6]:
np1 = np.ones(9).reshape(3,3)
print("original array : \n",np1)
np2 = np.zeros(25).reshape(5,5)
np2[1:4,1:4]=np1
np1 = np2
print("Expected array : \n",np1)

original array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Expected array : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern. Checkerboard pattern: 
[[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0] 
[0 1 0 1 0 1 0 1] 
[1 0 1 0 1 0 1 0]] 

In [7]:
np1 = np.zeros(64).reshape(8,8)
np1[1::2, ::2] = 1
np1[::2, 1::2] = 1
print(np1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays. 
List to array: 
[1 2 3 4 5 6 7 8] 
Tuple to array: 
[[8 4 6] 
[1 2 3]] 

In [8]:
tup = (1,2,3,4,5,6,7,8)
print(tup)
lst = list(tup)
print(lst)
print("tuple to array",np.array(tup))
print("list to array",np.array(lst))

(1, 2, 3, 4, 5, 6, 7, 8)
[1, 2, 3, 4, 5, 6, 7, 8]
tuple to array [1 2 3 4 5 6 7 8]
list to array [1 2 3 4 5 6 7 8]


9. Write a Python program to append values to the end of an array. Expected Output: 
Original array: 
[10, 20, 30]
After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90] 

In [9]:
np1 = np.array([10,20,30])
np2 = np.array([40,50,60,70,80,90])
np3 = np.append(np1,np2)
print("Original Array : ",np1)
print("Expected Array : ",np3)

Original Array :  [10 20 30]
Expected Array :  [10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex numbers. 
Expected Output: 
Original array [ 1.00000000+0.j 0.70710678+0.70710678j] 
Real part of the array: 
[ 1. 0.70710678] 
Imaginary part of the array: 
[ 0. 0.70710678] 


In [10]:
np1 = np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
print("Original Array : ",np1)
real_part = np.real(np1)
print("Real part of the array: ",real_part)
imag_part = np.imag(np1)
print("Imaginary part of the array: ",imag_part)

Original Array :  [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:  [1.         0.70710678]
Imaginary part of the array:  [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 
Expected Output: 
Size of the array: 3 
Length of one array element in bytes: 8 
Total bytes consumed by the elements of the array: 24 


In [11]:
np1 = np.array([1,2,3])
print("Size of the array: ",np1.size)
print("Length of one array element in bytes: ",np1.itemsize)
print("Total bytes consumed by the elements of the array: ",np1.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


12. Write a Python program to find common values between two arrays. Expected Output: 
Array1: [ 0 10 20 40 60] 
Array2: [10, 30, 40] 
Common values between two arrays: 
[10 40] 

In [12]:
np1 = np.array([0 ,10,20,40,60])
np2 = np.array([10,30,40])
print("Intersect :",np.intersect1d(np1,np2))

Intersect : [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Expected Output: 
Array1: [ 0 10 20 40 60 80] 
Array2: [10, 30, 40, 50, 70, 90] 
Set difference between two arrays: 
[ 0 20 60 80] 

In [13]:
np1 = np.array([ 0,10, 20 ,40, 60, 80])
np2 = np.array([10, 30, 40, 50, 70, 90])
print("set_difference",np.setdiff1d(np1,np2))

set_difference [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. Array1: [ 0 10 20 40 60 80] 
Array2: [10, 30, 40, 50, 70] 
Unique values that are in only one (not both) of the input arrays: 
[ 0 20 30 50 60 70 80]


In [14]:
np1 = np.array([0, 10, 20, 40, 60, 80])
np2 = np.array([10, 30, 40, 50, 70])
setxor = np.setxor1d(np1,np2)
print("Unique values that are in only one (not both) of the input arrays:\n",setxor)

Unique values that are in only one (not both) of the input arrays:
 [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy. 
Array a: [1 2] 
Array b: [4 5] 

In [31]:
a = np.array([1,2])
b = np.array([4,5])
print("a>b : ",a>b)
print("a==b : ",a==b)
print("a<b : ",a<b)
print("a<=b : ",a<=b)

a>b :  [False False]
a==b :  [False False]
a<b :  [ True  True]
a<=b :  [ True  True]


16. Write a Python program to save a NumPy array to a text file. 

In [16]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


17. Write a Python program to create a contiguous flattened array. Original array: 
[[10 20 30] 
[20 40 50]] 
New flattened array: 
[10 20 30 20 40 50] 

In [17]:
a = np.array([[10, 20, 30] ,[20, 40, 50]] )
print("a : \n",a)
print("flatten array :",a.reshape(-1))
print("flatten array :",a.flatten())

a : 
 [[10 20 30]
 [20 40 50]]
flatten array : [10 20 30 20 40 50]
flatten array : [10 20 30 20 40 50]


17. Write a Python program to change the data type of an array. Expected Output: 
[[ 2 4 6] 
[ 6 8 10]] 
Data type of the array x is: int32 
New Type: float64 
[[ 2. 4. 6.] 
[ 6. 8. 10.]] 


In [18]:
a = np.array([[ 2, 4, 6] ,[ 6, 8, 10]],dtype=np.int32 )
print("a and its Data type of the array:\n",a,a.dtype)
b = np.array(a,dtype=np.float64)
print("b and its Data type of the array:\n",b,b.dtype)

a and its Data type of the array:
 [[ 2  4  6]
 [ 6  8 10]] int32
b and its Data type of the array:
 [[ 2.  4.  6.]
 [ 6.  8. 10.]] float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere. 
Expected Output: 
[[ 1. 0. 0.] 
[ 0. 1. 0.] 
[ 0. 0. 1.]] 

In [19]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array. Expected Output: 
[[ 0. 0. 0.] 
[ 1. 0. 0.] 
[ 1. 1. 0.]
[ 1. 1. 1.]] 

In [20]:
a = np.zeros(12).reshape(4,3)
for i in range(4):
    for j in range(min(i+1,3)):
        a[i,j]=1
print(a)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays. Expected Output: 
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]] 
Expected Output: 
[[ 0 1 3 0 2 4] 
[ 5 7 9 6 8 10]] 

In [33]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
concatenated_array = np.concatenate((a, b), axis=1)
print("Sample arrays:")
print("Array 1:")
print(a)
print("Array 2:")
print(b)
print("\nExpected Output:")
print(concatenated_array)

Sample arrays:
Array 1:
[[0 1 3]
 [5 7 9]]
Array 2:
[[ 0  2  4]
 [ 6  8 10]]

Expected Output:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only). Expected Output: 
Test the array is read-only or not: 
Try to change the value of the first element: 
Traceback (most recent call last): 
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in 
x[0] = 1 
ValueError: assignment destination is read-only 

In [22]:
a = np.array([0, 1, 2, 3, 4])
# Make the array read-only
a.flags.writeable = False
print("Test the array is read-only or not:")
print("Is the array read-only?", not a.flags.writeable)
try:
    print("Try to change the value of the first element:")
    a[0] = 1 
except ValueError as e:
    print("Error:", e)


Test the array is read-only or not:
Is the array read-only? True
Try to change the value of the first element:
Error: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array. 
Expected Output: 
Original array elements: 
[[ 0 1 2 3] 
[ 4 5 6 7] 
[ 8 9 10 11]] 
New array elements: 
[[ 0 3 6 9] 
[12 15 18 21] 
[24 27 30 33]] 

In [23]:
a = np.array([[ 0 ,1 ,2 ,3], [ 4 ,5 ,6 ,7], [ 8 ,9 ,10 ,11]])
print(a*3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure. Expected Output: 
Original array elements: 
[[0 1] 
[2 3] 
[4 5]] 
Array to list: 
[[0, 1], [2, 3], [4, 5]] 

In [24]:
a = np.array([[0, 1], [2, 3], [4, 5]])
print("Original array elements:")
print(a)
lst = a.tolist()
print("\nArray to list:")
print(lst)

Original array elements:
[[0 1]
 [2 3]
 [4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure. 
Original array elements: 
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349 0.35399976 0.99469633 0.0694458 0.54711478] 
Print array values with precision 3:
Expected Output:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547] 

In [25]:
a = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478] )
np.set_printoptions(precision=3)
print(a)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array. 
Expected Output: 
Original array elements: 
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01] 
Print array values with precision 3: 
[ 0. 1.6 1200. 0.235] 

In [26]:
a = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01] )
np.set_printoptions(suppress=True,precision=3)
print(a)

[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array. 
Expected Output: 
[[ 10 20 30 100] 
[ 40 50 60 200]] 

In [27]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array : ",a)
col = np.array([[100], [200]])
b = np.hstack((a, col))
print("New Array : \n",b)

Original array :  [[10 20 30]
 [40 50 60]]
New Array : 
 [[ 10  20  30 100]
 [ 40  50  60 200]]


In [28]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(a)
indices_to_delete = [0, 3, 4]
b = np.delete(a, indices_to_delete)
print("\nDelete first, fourth and fifth elements:")
print(b)


Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]


In [ ]:
def numSquareSum(n):
    num = 0
    while(n):
        digit = n % 10
        num = num + digit*digit
        n = n // 10
    return num


def isHappyNumber(n):
    st = set()
    while (1):
        n = numSquareSum(n)
        if (n == 1):
            return True
        if n not in st:
            return False
        st.insert(n)
n=int(input())
y=isHappyNumber(n)

: 